// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {NodeProp} from "@lezer/common"
const spec_identifier = {__proto__:null,if:48, function:56, end:58, else:60, forever:62, times:64}
export const parser = LRParser.deserialize({
  version: 13,
  states: "&YOtQPOOOOQO'#C`'#C`O!pQPO'#CuOOQO'#Cu'#CuO{QPO'#CuOOQO'#Cr'#CrOOQO'#Cj'#CjO!zQPO'#C^QOQPOOOOQO'#Ch'#ChO#XQPO'#CeO#^QPO'#C_O#oQPO'#CgO#tQPO,59OO#^QPO,59TO#{QPO,59ROOQO-E6h-E6hO$SQPO,59PO$[QPO'#CuO%SQPO,58yOOQO'#Ck'#CkO%^QPO1G.jOOQO1G.j1G.jOOQO1G.o1G.oO%eQPO1G.mOOQO'#Cl'#ClO%jQPO'#CfO%rQPO1G.kO%wQPO1G.eOOQO-E6i-E6iOOQO7+$U7+$UOOQO7+$X7+$XOOQO-E6j-E6jO#{QPO7+$VOOQO7+$P7+$PO#{QPO7+$PO&PQPO<<GqO&UQPO<<GkOOQOAN=]AN=]OOQOAN=VAN=V",
  stateData: "&Z~OcOSdOSeOS~OTROUSOVROgPOhZOlYOoXO~OaQP~P]Op_OTiXUiXViXaiXgiXhiXliXoiXmiXniX~Oj]Oq^O~P{OaQXmQXnQX~P]OjaO~OTROUROVROgPOlYO~Op_O~OkfO~P#^OmQP~P]OgPOkYP~Oj]OTiXUiXViXgiXhiXliXmiXniXoiXkiXaiX~OmQPnQP~P]OknO~P#^OmoO~OgPOkYX~OkqO~OmrOnsO~OmvO~OmwO~O",
  goto: "$PjPPkz!SPPP!f!f!rz!uz!}#X#_PPPPP#ePP#mQWOQh_QlcQtqRus]TOV_cqs[QOV_cqsWbZ]^eTiajeROVZ]^_ceqsRka][OV_cqsYVO_cqsR`VQe]RmeQjaRpj]UOV_cqs[TOV_cqsQcZSd]eRg^",
  nodeNames: "⚠ Program Block IfStatement Symbol Boolean Number Null CallExpression Function SymbolList TimesStatement Forever SetStatement",
  maxTerm: 33,
  nodeProps: [
    [NodeProp.closedBy, 3,"end else",9,"end"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: ")Y~RhX^!mpq!mxy#byz#g|}#l!P!Q#q!Q![$S!_!`$[!c!}$a#T#Y$a#Y#Z$o#Z#b$a#b#c&p#c#h$a#h#i(`#i#o$a#y#z!m$f$g!m#BY#BZ!m$IS$I_!m$I|$JO!m$JT$JU!m$KV$KW!m&FU&FV!m~!rYd~X^!mpq!m#y#z!m$f$g!m#BY#BZ!m$IS$I_!m$I|$JO!m$JT$JU!m$KV$KW!m&FU&FV!m~#gOj~~#lOk~~#qOc~~#tP!P!Q#w~#|Qe~OY#wZ~#w~$XPU~!Q![$S~$aOq~~$fRg~!Q![$a!c!}$a#T#o$a~$tSg~!Q![$a!c!}$a#T#U%Q#U#o$a~%VTg~!Q![$a!c!}$a#T#`$a#`#a%f#a#o$a~%kTg~!Q![$a!c!}$a#T#g$a#g#h%z#h#o$a~&PTg~!Q![$a!c!}$a#T#X$a#X#Y&`#Y#o$a~&gRT~g~!Q![$a!c!}$a#T#o$a~&uTg~!Q![$a!c!}$a#T#i$a#i#j'U#j#o$a~'ZTg~!Q![$a!c!}$a#T#`$a#`#a'j#a#o$a~'oTg~!Q![$a!c!}$a#T#`$a#`#a(O#a#o$a~(VRV~g~!Q![$a!c!}$a#T#o$a~(eTg~!Q![$a!c!}$a#T#f$a#f#g(t#g#o$a~(yTg~!Q![$a!c!}$a#T#i$a#i#j%z#j#o$a",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 23, get: value => spec_identifier[value] || -1}],
  tokenPrec: 0
})
