// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {NodeProp} from "@lezer/common"
const spec_identifier = {__proto__:null,if:52, function:60, end:62, else:64, forever:66, times:68}
export const parser = LRParser.deserialize({
  version: 13,
  states: "&lO]QPOOOOQO'#C`'#C`OnQPO'#CkOOQO'#Ct'#CtOOQO'#Cl'#ClO!`QPO'#C^QOQPOOOOQO'#Ci'#CiO!wQPO'#C_O#]QPO'#ChO!wQPO,59UO#bQPO,59VO#iQPO,59SOOQO-E6j-E6jO#zQPO'#CwOOQO'#Cw'#CwO$uQPO'#CfO$zQPO,58yOOQO1G.p1G.pOOQO'#Cm'#CmO%RQPO1G.qOOQO1G.q1G.qO%YQPO1G.nO%_QPO,59PO%fQPO,59QO%nQPO1G.eOOQO-E6k-E6kOOQO7+$]7+$]OOQO7+$Y7+$YO%vQPO1G.kOOQO1G.k1G.kOOQO'#Cn'#CnO%}QPO'#CgO&VQPO1G.lOOQO7+$P7+$PO#iQPO7+$POOQO7+$V7+$VOOQO-E6l-E6lO#iQPO7+$WO&[QPO<<GkO&aQPO<<GrOOQOAN=VAN=VOOQOAN=^AN=^",
  stateData: "&f~OeOSfOSgOS~OVXOiPOjWOqVOcQP~OlZOr[OsYOV_Xc_Xi_Xj_Xq_Xo_Xp_X~OVXOiPOjWOqVOcQXoQXpQX~OT_OU_OV_OW_OiPOn`O~Or[O~OmeO~P!wOVXOiPOjWOqVOoQP~OlgOVkXikXjkXokXpkXqkXckXTkXUkXWkXmkXnkX~OlhO~OpQP~P#iOmkO~P!wOolO~OmnO~P!wOiPOmZP~OorOpsO~OmtO~P!wOiPOmZX~OmvO~OoyO~OozO~O",
  goto: "#}lPPm|!UPPPP!j!j!r|!u||!}#X#cPPPPP#iPP#qQUOQf[QiaQwsRxv]ROT[asv[QOT[asv[^WYZdgmTohp]_WYZdgmRqh]XOT[asvYTO[asvR]TQdZSjdmRmgQphRup]SOT[asvQaWQbYXcZdgm",
  nodeNames: "⚠ Program Block IfStatement Symbol Boolean String Number Null CallExpression Function SymbolList TimesStatement Forever SetStatement CallStatement",
  maxTerm: 35,
  nodeProps: [
    [NodeProp.closedBy, -3,3,10,12,"end"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "*m~RjX^!spq!srs#hwx$Yxy$uyz$z|}%P!P!Q%U!Q![%g!_!`%o!c!}%t#T#Y%t#Y#Z&S#Z#b%t#b#c(T#c#h%t#h#i)s#i#o%t#y#z!s$f$g!s#BY#BZ!s$IS$I_!s$I|$JO!s$JT$JU!s$KV$KW!s&FU&FV!s~!xYf~X^!spq!s#y#z!s$f$g!s#BY#BZ!s$IS$I_!s$I|$JO!s$JT$JU!s$KV$KW!s&FU&FV!s~#kUOY#hZr#hrs#}s#O#h#O#P$S#P~#h~$SOU~~$VPO~#h~$]UOY$YZw$Ywx#}x#O$Y#O#P$o#P~$Y~$rPO~$Y~$zOl~~%POm~~%UOe~~%XP!P!Q%[~%aQg~OY%[Z~%[~%lPV~!Q![%g~%tOs~~%yRi~!Q![%t!c!}%t#T#o%t~&XSi~!Q![%t!c!}%t#T#U&e#U#o%t~&jTi~!Q![%t!c!}%t#T#`%t#`#a&y#a#o%t~'OTi~!Q![%t!c!}%t#T#g%t#g#h'_#h#o%t~'dTi~!Q![%t!c!}%t#T#X%t#X#Y's#Y#o%t~'zRT~i~!Q![%t!c!}%t#T#o%t~(YTi~!Q![%t!c!}%t#T#i%t#i#j(i#j#o%t~(nTi~!Q![%t!c!}%t#T#`%t#`#a(}#a#o%t~)STi~!Q![%t!c!}%t#T#`%t#`#a)c#a#o%t~)jRW~i~!Q![%t!c!}%t#T#o%t~)xTi~!Q![%t!c!}%t#T#f%t#f#g*X#g#o%t~*^Ti~!Q![%t!c!}%t#T#i%t#i#j'_#j#o%t",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 25, get: value => spec_identifier[value] || -1}],
  tokenPrec: 0
})
