// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Block = 2,
  Symbol = 4,
  Boolean = 5,
  String = 6,
  Number = 7,
  Null = 8,
  SymbolList = 11,
  Forever = 13,
  CallStatement = 15
