// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Block = 2,
  Symbol = 4,
  Boolean = 5,
  Number = 6,
  Null = 7,
  SymbolList = 10,
  Forever = 12
