// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Statement = 3,
  IfExpression = 4,
  Condition = 5,
  TimesExpression = 6,
  Number = 7
